// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.distracted.tracker.model;

import java.util.List;
import java.util.Random;
import org.distracted.tracker.model.Project;
import org.springframework.stereotype.Component;

privileged aspect ProjectDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectDataOnDemand: @Component;
    
    private Random ProjectDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Project> ProjectDataOnDemand.data;
    
    public Project ProjectDataOnDemand.getNewTransientProject(int index) {
        org.distracted.tracker.model.Project obj = new org.distracted.tracker.model.Project();
        java.lang.String projectName = "projectName_" + index;
        if (projectName.length() > 40) {
            projectName  = projectName.substring(0, 40);
        }
        obj.setProjectName(projectName);
        return obj;
    }
    
    public Project ProjectDataOnDemand.getSpecificProject(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Project obj = data.get(index);
        return Project.findProject(obj.getId());
    }
    
    public Project ProjectDataOnDemand.getRandomProject() {
        init();
        Project obj = data.get(rnd.nextInt(data.size()));
        return Project.findProject(obj.getId());
    }
    
    public boolean ProjectDataOnDemand.modifyProject(Project obj) {
        return false;
    }
    
    public void ProjectDataOnDemand.init() {
        data = new java.util.ArrayList<org.distracted.tracker.model.Project>();
        for (int i = 0; i < 10; i++) {
            org.distracted.tracker.model.Project obj = getNewTransientProject(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
