// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.distracted.tracker.model;

import org.distracted.tracker.model.SimpleTaskDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SimpleTaskIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SimpleTaskIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SimpleTaskIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SimpleTaskIntegrationTest: @Transactional;
    
    @Autowired
    private SimpleTaskDataOnDemand SimpleTaskIntegrationTest.dod;
    
    @Test
    public void SimpleTaskIntegrationTest.testCountSimpleTasks() {
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to initialize correctly", dod.getRandomSimpleTask());
        long count = org.distracted.tracker.model.SimpleTask.countSimpleTasks();
        org.junit.Assert.assertTrue("Counter for 'SimpleTask' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SimpleTaskIntegrationTest.testFindSimpleTask() {
        org.distracted.tracker.model.SimpleTask obj = dod.getRandomSimpleTask();
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.SimpleTask.findSimpleTask(id);
        org.junit.Assert.assertNotNull("Find method for 'SimpleTask' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'SimpleTask' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SimpleTaskIntegrationTest.testFindAllSimpleTasks() {
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to initialize correctly", dod.getRandomSimpleTask());
        long count = org.distracted.tracker.model.SimpleTask.countSimpleTasks();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'SimpleTask', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.distracted.tracker.model.SimpleTask> result = org.distracted.tracker.model.SimpleTask.findAllSimpleTasks();
        org.junit.Assert.assertNotNull("Find all method for 'SimpleTask' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'SimpleTask' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SimpleTaskIntegrationTest.testFindSimpleTaskEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to initialize correctly", dod.getRandomSimpleTask());
        long count = org.distracted.tracker.model.SimpleTask.countSimpleTasks();
        if (count > 20) count = 20;
        java.util.List<org.distracted.tracker.model.SimpleTask> result = org.distracted.tracker.model.SimpleTask.findSimpleTaskEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'SimpleTask' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'SimpleTask' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SimpleTaskIntegrationTest.testFlush() {
        org.distracted.tracker.model.SimpleTask obj = dod.getRandomSimpleTask();
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.SimpleTask.findSimpleTask(id);
        org.junit.Assert.assertNotNull("Find method for 'SimpleTask' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySimpleTask(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'SimpleTask' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SimpleTaskIntegrationTest.testMerge() {
        org.distracted.tracker.model.SimpleTask obj = dod.getRandomSimpleTask();
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.SimpleTask.findSimpleTask(id);
        boolean modified =  dod.modifySimpleTask(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.distracted.tracker.model.SimpleTask merged = (org.distracted.tracker.model.SimpleTask) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'SimpleTask' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SimpleTaskIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to initialize correctly", dod.getRandomSimpleTask());
        org.distracted.tracker.model.SimpleTask obj = dod.getNewTransientSimpleTask(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'SimpleTask' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'SimpleTask' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SimpleTaskIntegrationTest.testRemove() {
        org.distracted.tracker.model.SimpleTask obj = dod.getRandomSimpleTask();
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SimpleTask' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.SimpleTask.findSimpleTask(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'SimpleTask' with identifier '" + id + "'", org.distracted.tracker.model.SimpleTask.findSimpleTask(id));
    }
    
}
