// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.distracted.tracker.model;

import org.distracted.tracker.model.TaskExtendedAttributesDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TaskExtendedAttributesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TaskExtendedAttributesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TaskExtendedAttributesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TaskExtendedAttributesIntegrationTest: @Transactional;
    
    @Autowired
    private TaskExtendedAttributesDataOnDemand TaskExtendedAttributesIntegrationTest.dod;
    
    @Test
    public void TaskExtendedAttributesIntegrationTest.testCountTaskExtendedAttributeses() {
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to initialize correctly", dod.getRandomTaskExtendedAttributes());
        long count = org.distracted.tracker.model.TaskExtendedAttributes.countTaskExtendedAttributeses();
        org.junit.Assert.assertTrue("Counter for 'TaskExtendedAttributes' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TaskExtendedAttributesIntegrationTest.testFindTaskExtendedAttributes() {
        org.distracted.tracker.model.TaskExtendedAttributes obj = dod.getRandomTaskExtendedAttributes();
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.TaskExtendedAttributes.findTaskExtendedAttributes(id);
        org.junit.Assert.assertNotNull("Find method for 'TaskExtendedAttributes' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'TaskExtendedAttributes' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TaskExtendedAttributesIntegrationTest.testFindAllTaskExtendedAttributeses() {
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to initialize correctly", dod.getRandomTaskExtendedAttributes());
        long count = org.distracted.tracker.model.TaskExtendedAttributes.countTaskExtendedAttributeses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'TaskExtendedAttributes', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.distracted.tracker.model.TaskExtendedAttributes> result = org.distracted.tracker.model.TaskExtendedAttributes.findAllTaskExtendedAttributeses();
        org.junit.Assert.assertNotNull("Find all method for 'TaskExtendedAttributes' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'TaskExtendedAttributes' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TaskExtendedAttributesIntegrationTest.testFindTaskExtendedAttributesEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to initialize correctly", dod.getRandomTaskExtendedAttributes());
        long count = org.distracted.tracker.model.TaskExtendedAttributes.countTaskExtendedAttributeses();
        if (count > 20) count = 20;
        java.util.List<org.distracted.tracker.model.TaskExtendedAttributes> result = org.distracted.tracker.model.TaskExtendedAttributes.findTaskExtendedAttributesEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'TaskExtendedAttributes' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'TaskExtendedAttributes' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TaskExtendedAttributesIntegrationTest.testFlush() {
        org.distracted.tracker.model.TaskExtendedAttributes obj = dod.getRandomTaskExtendedAttributes();
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.TaskExtendedAttributes.findTaskExtendedAttributes(id);
        org.junit.Assert.assertNotNull("Find method for 'TaskExtendedAttributes' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTaskExtendedAttributes(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'TaskExtendedAttributes' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaskExtendedAttributesIntegrationTest.testMerge() {
        org.distracted.tracker.model.TaskExtendedAttributes obj = dod.getRandomTaskExtendedAttributes();
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.TaskExtendedAttributes.findTaskExtendedAttributes(id);
        boolean modified =  dod.modifyTaskExtendedAttributes(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.distracted.tracker.model.TaskExtendedAttributes merged = (org.distracted.tracker.model.TaskExtendedAttributes) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'TaskExtendedAttributes' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaskExtendedAttributesIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to initialize correctly", dod.getRandomTaskExtendedAttributes());
        org.distracted.tracker.model.TaskExtendedAttributes obj = dod.getNewTransientTaskExtendedAttributes(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'TaskExtendedAttributes' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'TaskExtendedAttributes' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TaskExtendedAttributesIntegrationTest.testRemove() {
        org.distracted.tracker.model.TaskExtendedAttributes obj = dod.getRandomTaskExtendedAttributes();
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'TaskExtendedAttributes' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.TaskExtendedAttributes.findTaskExtendedAttributes(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'TaskExtendedAttributes' with identifier '" + id + "'", org.distracted.tracker.model.TaskExtendedAttributes.findTaskExtendedAttributes(id));
    }
    
}
