// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.distracted.tracker.model;

import java.util.List;
import java.util.Random;
import org.distracted.tracker.model.TaskExtendedAttributes;
import org.springframework.stereotype.Component;

privileged aspect TaskExtendedAttributesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TaskExtendedAttributesDataOnDemand: @Component;
    
    private Random TaskExtendedAttributesDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<TaskExtendedAttributes> TaskExtendedAttributesDataOnDemand.data;
    
    public TaskExtendedAttributes TaskExtendedAttributesDataOnDemand.getNewTransientTaskExtendedAttributes(int index) {
        org.distracted.tracker.model.TaskExtendedAttributes obj = new org.distracted.tracker.model.TaskExtendedAttributes();
        java.lang.String comments = "comments_" + index;
        if (comments.length() > 1000) {
            comments  = comments.substring(0, 1000);
        }
        obj.setComments(comments);
        obj.setCost(null);
        obj.setLastUpdateDate(new java.util.Date());
        return obj;
    }
    
    public TaskExtendedAttributes TaskExtendedAttributesDataOnDemand.getSpecificTaskExtendedAttributes(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        TaskExtendedAttributes obj = data.get(index);
        return TaskExtendedAttributes.findTaskExtendedAttributes(obj.getId());
    }
    
    public TaskExtendedAttributes TaskExtendedAttributesDataOnDemand.getRandomTaskExtendedAttributes() {
        init();
        TaskExtendedAttributes obj = data.get(rnd.nextInt(data.size()));
        return TaskExtendedAttributes.findTaskExtendedAttributes(obj.getId());
    }
    
    public boolean TaskExtendedAttributesDataOnDemand.modifyTaskExtendedAttributes(TaskExtendedAttributes obj) {
        return false;
    }
    
    public void TaskExtendedAttributesDataOnDemand.init() {
        data = new java.util.ArrayList<org.distracted.tracker.model.TaskExtendedAttributes>();
        for (int i = 0; i < 10; i++) {
            org.distracted.tracker.model.TaskExtendedAttributes obj = getNewTransientTaskExtendedAttributes(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
