// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.distracted.tracker.model;

import org.distracted.tracker.model.TaskDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TaskIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TaskIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TaskIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TaskIntegrationTest: @Transactional;
    
    @Autowired
    private TaskDataOnDemand TaskIntegrationTest.dod;
    
    @Test
    public void TaskIntegrationTest.testCountTasks() {
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to initialize correctly", dod.getRandomTask());
        long count = org.distracted.tracker.model.Task.countTasks();
        org.junit.Assert.assertTrue("Counter for 'Task' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TaskIntegrationTest.testFindTask() {
        org.distracted.tracker.model.Task obj = dod.getRandomTask();
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.Task.findTask(id);
        org.junit.Assert.assertNotNull("Find method for 'Task' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Task' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TaskIntegrationTest.testFindAllTasks() {
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to initialize correctly", dod.getRandomTask());
        long count = org.distracted.tracker.model.Task.countTasks();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Task', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.distracted.tracker.model.Task> result = org.distracted.tracker.model.Task.findAllTasks();
        org.junit.Assert.assertNotNull("Find all method for 'Task' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Task' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TaskIntegrationTest.testFindTaskEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to initialize correctly", dod.getRandomTask());
        long count = org.distracted.tracker.model.Task.countTasks();
        if (count > 20) count = 20;
        java.util.List<org.distracted.tracker.model.Task> result = org.distracted.tracker.model.Task.findTaskEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Task' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Task' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TaskIntegrationTest.testFlush() {
        org.distracted.tracker.model.Task obj = dod.getRandomTask();
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.Task.findTask(id);
        org.junit.Assert.assertNotNull("Find method for 'Task' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTask(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Task' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaskIntegrationTest.testMerge() {
        org.distracted.tracker.model.Task obj = dod.getRandomTask();
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.Task.findTask(id);
        boolean modified =  dod.modifyTask(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.distracted.tracker.model.Task merged = (org.distracted.tracker.model.Task) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Task' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaskIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to initialize correctly", dod.getRandomTask());
        org.distracted.tracker.model.Task obj = dod.getNewTransientTask(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Task' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Task' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TaskIntegrationTest.testRemove() {
        org.distracted.tracker.model.Task obj = dod.getRandomTask();
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Task' failed to provide an identifier", id);
        obj = org.distracted.tracker.model.Task.findTask(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Task' with identifier '" + id + "'", org.distracted.tracker.model.Task.findTask(id));
    }
    
}
